=== szally/ZVC5K4_XMLGyak/ZVC5K4_1109/hallgatokZVC5K4.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="keresztnév" type="xs:string"/>
                            <xs:element name="vezetéknév" type="xs:string"/>
                            <xs:element name="becenév" type="xs:string"/>
                            <xs:element name="kor" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== szally/ZVC5K4_XMLGyak/ZVC5K4_1109/hallgatokZVC5K4.xml
<?xml version="1.0" encoding="UTF-8"?>

<class  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="hallgatokZVC5K4.xsd">
    <student id="01">
        <keresztnév>Endre</keresztnév>
        <vezetéknév>Kovács</vezetéknév>
        <becenév>Bandi</becenév>
        <kor>35</kor>
    </student>
    <student id="02">
        <keresztnév>Anita</keresztnév>
        <vezetéknév>Nagy</vezetéknév>
        <becenév>Ancsi</becenév>
        <kor>19</kor>
    </student>
    <student id="03">
        <keresztnév>Olga</keresztnév>
        <vezetéknév>Kertész</vezetéknév>
        <becenév>Olgi</becenév>
        <kor>40</kor>
    </student>
</class>
